import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { GitHubLogoIcon } from "@radix-ui/react-icons";

const font = IBM_Plex_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["200", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "KPS Exams Table ✨",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", font.className)}>
        <Providers>
          <main className="min-h-screen xl:px-96 py-4 px-4 w-full space-y-5">
            <Navbar />
            {children}
          </main>
          <footer className="w-full">
            <div className="bg-primary text-center text-white p-2">
              <a
                href="https://discord.gg/vfTDdjtr"
                className="underline"
                target="_blank"
              >
                แจ้งปัญหา / อัพเดทข้อมูล ทาง Discord
              </a>
            </div>
            <div className="bg-primary/95 p-2 hidden xl:block">
              <a
                href="https://github.com/nokamui123/kps-exams-table"
                target="_blank"
                className="flex gap-2 items-center justify-center text-white"
              >
                <GitHubLogoIcon /> Source Code
              </a>
            </div>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
