import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

const font = IBM_Plex_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["200", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "KPS Exams Table ✨",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", font.className)}>
        <Providers>
          <main className="min-h-screen xl:px-96 py-4 px-4 w-full space-y-5">
            <Navbar />
            {children}
          </main>
          <footer className="bg-primary text-white text-center p-2">
            <a href="https://discord.gg/P5snQfWB" className="underline">
              แจ้งปัญหา / อัพเดทข้อมูล ทาง Discord
            </a>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
